export const REQUEST_GET_PREFERENCES = "REQUEST_GET_PREFERENCES";
export const SUCCESS_GET_PREFERENCES = "SUCCESS_GET_PREFERENCES";
export const ERROR_GET_PREFERENCES = "ERROR_GET_PREFERENCES";
export const REQUEST_EDIT_PREFERENCES = "REQUEST_EDIT_PREFERENCES";
export const SUCCESS_EDIT_PREFERENCES = "SUCCESS_EDIT_PREFERENCES";
export const ERROR_EDIT_PREFERENCES = "ERROR_EDIT_PREFERENCES";
