export const REQUEST_VALIDATE_INVITATION = "REQUEST_VALIDATE_INVITATION";
export const SUCCESS_VALIDATE_INVITATION = "SUCCESS_VALIDATE_INVITATION";
export const ERROR_VALIDATE_INVITATION = "ERROR_VALIDATE_INVITATION";
